### ISSUE TITLE
Block Place won't get logged if chunk claim is not enabled

### ISSUE THREAD

**Issue by stdcall0** [GStefanowich/MC-Server-Protection#13]
In MC-Server-Protection/src/main/java/net/TheElm/project/protections/events/BlockInteraction.java, it checks if chunk claim is enabled. If it is disabled, it simply exits and doesn't trigger BlockInteraction, results in block place not get logged.

**Comment by GStefanowich** [comment]
Thanks for bringing this to my attention. The way I wrote it, I hadn't thought about this problem. I'll make sure it's fixed for the next 1.15 release.

**Comment by stdcall0** [comment]
Ok thanks for that.

**Comment by GStefanowich** [comment]
Fixed in ebe2c5c
[Latest release 1.2.0](https://github.com/GStefanowich/MC-Server-Protection/releases/tag/v1.2.0)
