### ISSUE TITLE
1.16.1 Update

### ISSUE THREAD

**Issue by SirOMGitsYOU** [GStefanowich/MC-Server-Protection#16]
Hey

Is there any progress for this for 1.16.1 fabric?

**Comment by GStefanowich** [comment]
It's being actively worked on when I have the free time. Modding is just something I do for fun in my spare time.

1.16 has a lot more changes from 1.15 than 1.15 did from 1.14, so updating is taking a little longer.

A lot was changed around Text, which a majority of my commands use a lot of. It also seems that in 1.16 mojang started withdrawing information about client languages, so pulling translations is a little harder.

**Comment by SirOMGitsYOU** [comment]
Is there any possibility of having the Chunk claiming feature ready for 1.16 any time soon? As I'm looking to release my new modpack on fabric 1.16 but there are currently 0 chunk claiming mods.

**Comment by SirOMGitsYOU** [comment]
Any more news on this 1.16 update?

**Comment by GStefanowich** [comment]
I've got free time this weekend, I'll see if I can have an update out for `1.16.2`. There are some new dupe bugs that I want to look into fixing

**Comment by SirOMGitsYOU** [comment]
> I've got free time this weekend, I'll see if I can have an update out for `1.16.2`. There are some new dupe bugs that I want to look into fixing

Is there any chance of a 1.16.1 version?

**Comment by GStefanowich** [comment]
> > I've got free time this weekend, I'll see if I can have an update out for `1.16.2`. There are some new dupe bugs that I want to look into fixing
> 
> Is there any chance of a 1.16.1 version?

When I was last working on it was for `1.16.1`, so if you would like a release for that version I'll continue on that first before updating to `.2`

**Comment by SirOMGitsYOU** [comment]
> > > I've got free time this weekend, I'll see if I can have an update out for `1.16.2`. There are some new dupe bugs that I want to look into fixing
> > 
> > 
> > Is there any chance of a 1.16.1 version?
> 
> When I was last working on it was for `1.16.1`, so if you would like a release for that version I'll continue on that first before updating to `.2`

yeah if possible, :)

**Comment by SirOMGitsYOU** [comment]
How's progress coming on the 1.16.1 build? :)

**Comment by GStefanowich** [comment]
Unless there's a special need for a 1.16.1 version, only the latest 1.16.5 version will be getting a release. Should be coming soon
