### ISSUE TITLE
Are There Custom Build Directions?

### ISSUE THREAD

**Issue by ZombieNW** [GStefanowich/MC-Server-Protection#19]
I've taken this into Idea and I've gotten it working on Minecraft Server debugging but as soon as I try to build it it either doesn't work or the mods outputted don't work. Are there special building instructions? I'm just trying to update this to 1.16.4/5, and patched together bugs that prevented it from starting. It worked in debugging but as soon as I built it it gives me errors that I didn't have while debugging, so is there a special build command or something? Sorry to bother you

**Comment by GStefanowich** [comment]
There's nothing special to the build, I use Gradle to perform the build

I just pushed my latest code to the repo, I'll upload a release here in a minute to the releases page. Keep an eye out for it.

I'll first be opening some Issues that are bugs that currently exist. Just be mindful of those when updating your server.
