### ISSUE TITLE
[Maybe Suggestion] Way to add items to chest shops

### ISSUE THREAD

**Issue by ZombieNW** [GStefanowich/MC-Server-Protection#32]
On line 2 you have to put the number then the item, but the line usually isn't long enough.
Things like
"1 enchanted_book" or "64 dark_oak_planks" are too long.
So maybe something like a command to add the item that you're holding? Or a tag like "[chest]" on line 2 that automatically sets it to the first item in the chest and sets it to that.

**Comment by GStefanowich** [comment]
Currently if you place an item in your off-hand, and place the sign using your main hand, you can add that item to the sign by typing "hand" for the item. Such as "32 hand", "12 hand", etc etc.

**Comment by GStefanowich** [comment]
You can see the [code responsible for this here](https://github.com/GStefanowich/MC-Server-Protection/blob/98bd1f36b0a5f441da639cf512fb6ca487c975d1/src/main/java/net/TheElm/project/utilities/ShopSignBuilder.java#L196-L211), but I'd also like to note that shop signs are very simple right now and don't do any NBT data matching *currently*.

So you can sell an "Enchanted book" and any enchanted book in the chest will be sold, it doesn't check for the enchantment in the NBT data.

The same goes for partially damaged items, any durability item can be sold as long as the item itself matches.

**Comment by ZombieNW** [comment]
"don't do any NBT data matching currently. So you can sell an "Enchanted book" and any enchanted book in the chest will be sold, it doesn't check for the enchantment in the NBT data."

Worked fine for me, matched the name and the enchantment. And the hand thing also worked thank you

**Comment by GStefanowich** [comment]
> Worked fine for me, matched the name and the enchantment.

Shop signs only save the Item Identifier, such as `minecraft:dirt`, `minecraft:stone_brick_stairs`, or `minecraft:enchantment_book`. As long as the item *is* a `minecraft:enchantment_book` it'll sell it if that's what is on the sign. So that includes the enchantment you *want* to sell, but if you throw any other enchantment into the same chest, it'll sell that too.

> And the hand thing also worked thank you

The rest of the [documentation can be seen here](https://www.curseforge.com/minecraft/mc-mods/sewing-machine-utilities/pages/shop-signs).

> *If an item name is too long to be written on the second line of the sign, place the item you want to buy/sell in your offhand and write "hand" in place of the item name.*

**Comment by ZombieNW** [comment]
Ohh Okay thank you, sorry for the bother
