### ISSUE TITLE
Update a few text files to make run in 1.18.x

### ISSUE THREAD

**Issue by TwoPointInfinity** [GStefanowich/MC-Server-Protection#36]
gradle.properties to https://pastebin.com/jrKr9jgF (i changed the link for the versions too)

line 4 of TheElm.mixins.json MUST BE "compatibilityLevel": "JAVA_16",

Fabric in 1.18 compatibility needs to say compatible with java 16. I know.. it literally runs on 17, but fabric doesn't care and if we don't do what they say our mods wont work.

**Comment by GStefanowich** [comment]
Strange, I've not personally had any issues in development nor on my personal server, but it appears that it's the same even in the Fabric example mod. Thanks for pointing this out

I'll release 1.18.1 shortly

**Comment by GStefanowich** [comment]
1.18.1 build is now available in releases using the proper compatibility
