### ISSUE TITLE
Crash - [SEW] Error executing MySQL Database setup

### ISSUE THREAD

**Issue by TwoPointInfinity** [GStefanowich/MC-Server-Protection#38]
https://pastebin.com/ReJmqfeh

this started after changing the config to line 155-162

```
  "logging": {
    "blocks": {
      "break": true,
      "place": true
    },
    "chunks": {
      "claimed": true,
      "wilderness": false
```

sqlite.db was created in \config\sewing-machine

also in the config line 75-81 

```
  "database": {
    "sqlite": true,
    "host": "",
    "name": "",
    "user": "",
    "pass": "",
    "port": 3306
```

**Comment by GStefanowich** [comment]
Thanks for reporting this, I really should disable the sqlite config option, it's been an open issue for awhile - #6 

The current sql setup uses data types that aren't supported by sqlite, and I need to adapt for that

**Comment by TwoPointInfinity** [comment]
oh okay. how do we use block logging without sqlite? Is that feature available i would really like that.

**Comment by GStefanowich** [comment]
The only other option currently for block logging is to disable the sqlite option and enter the details into the database section for a SQL server

**Comment by TwoPointInfinity** [comment]
ah okay thank you. im not familiar with SQL.
