### ISSUE TITLE
[MAJOR ISSUE] Illegal enchantments by combining in anvil

### ISSUE THREAD

**Issue by AchalS-iglu** [GStefanowich/MC-Server-Protection#39]
Players in my server with this mod installed can craft illegal enchantments by combining them in anvil. For example they can combine two fort 3 pickaxes to make fortune 4 which works and is not just a text bug.

Refer to image.
![image](https://user-images.githubusercontent.com/45008879/146813349-2f2d3f93-4f8d-4f8e-9627-0b1e1173a988.png)

I am on 1.4.2 version of Sewing Machine while the server is on 1.18.1

Here are the other mods and datapacks I have in case it is a conflict:-

Chunky-l.2.153.jar
cloth-config-6.1.48-fabric.jar
disfabric-1.18-1.3.5.jar
essential—commands-O.17.1-mc1.18-rc3.jar
fabric-api-O.44.O+1.18.jar
fabric-carpet-l.18-1.4.56+v211130Jar
fabric-language-kotlin-1.7.O+kotIin .1.6.O.jar
fabrictailor-1.7.3.jar
fastfurnace-1.18-4.jar
gimme-bundles-fabric-1.O.4.jar
htm-1.1.4.jar
InventorySorter-1.8.1-1.18.jar
KeepHeadNames-1.5.1-fabric-1.18.jar
ledger-l.2.O.jar
lithium-fabric-mc1.18.1-O.7.6.jar
sewing-machine-l.4.2—mc-1.18.1.jar
sodium-fabric-mc1.18-O.4.O-alpha5+build9Jar
starlight-I.o.O+fabric.dOa3220.jar
textile-backup-2.3.O-1.18.jar
voicechat-fabric-1.18.1-2.1.22.jar

afk display vl.1.2.zip
anti enderman grief vl.1.2.zip
armor statues v2.8.3.zip
BlazeandCaves Advancements Pack 1.13.1.zip
double shulker shells vl.3.2.zip
fast leaf decay v2.O.5.zip
more mob heads v2.9.4.zip
multiplayer sleep v2.6.2.zip
nether portal coords vl.1.2.zip
player head drops vl.1.2.zip
silence mobs v112.zip
track raw statistics vl.5.2.zip
track statistics vl.1.3.zip
unlock all recipes v2.O.3.zip
wandering trades hermit edition vl.6.1.zip

Server log - https://pastebin.com/KqCD3ExQ
I removed chat since it wasn't letting me upload  :/

Here is my sewing machine config - https://pastebin.com/D8sstG9T
I tried setting both the anvil related settings to true and false

**Comment by GStefanowich** [comment]
Thanks for letting me know about this, I'm working on fixing it now. It may take some time.

**Comment by AchalS-iglu** [comment]
> Thanks for letting me know about this, I'm working on fixing it now. It may take some time.

Thank you!

**Comment by GStefanowich** [comment]
Fixed in commit 046a0dd71fb93e4a68362b5fb7adf38b65a21102, will be posting a new release shortly

**Comment by AchalS-iglu** [comment]
> Fixed in commit [046a0dd](https://github.com/GStefanowich/MC-Server-Protection/commit/046a0dd71fb93e4a68362b5fb7adf38b65a21102), will be posting a new release shortly

Thank you for the quick reply and update!
