### ISSUE TITLE
Block logging is unusable as the database type is forced to SQLite

### ISSUE THREAD

**Issue by Cecer** [GStefanowich/MC-Server-Protection#46]
The database type is forced to SQLite. As such, it is not possible to enable block logging.
This seems to be caused by [this change in 046a0dd](https://github.com/GStefanowich/MC-Server-Protection/commit/046a0dd71fb93e4a68362b5fb7adf38b65a21102#diff-2376898ccf1c7b42e40ae8b4b320f10cf388b78c0f156f3a1ed309e9c89a7be4L79-R79).

This appears to be why:
- `SewConfig.DB_LITE` defaults to true
- This change removed the call which passed `SewConfig.DB_LITE` to `SewConfig.addConfig(ConfigOption)`
- This means that `SewConfig.DB_LITE` is never added to the `SewConfigContainer.configOptions` list
https://github.com/GStefanowich/MC-Server-Protection/blob/4a01cbde0bb8c4c0634445ecdd689a326e91b4ab/src/main/java/net/TheElm/project/config/SewConfig.java#L387
- This means that when `SewConfig.loadFromJSON(JsonObject)` is finally called it never sets the value `database.sqlite` value into `SewConfig.DB_LITE` as it isn't in that list
https://github.com/GStefanowich/MC-Server-Protection/blob/4a01cbde0bb8c4c0634445ecdd689a326e91b4ab/src/main/java/net/TheElm/project/config/SewConfig.java#L489
- Therefore the value is not changed from the default of true
- As a result, `CoreMod.getSQL()` always returns an instance of `MySQLite` as `SewConfig.DB_LITE` is always set to true
https://github.com/GStefanowich/MC-Server-Protection/blob/82e295ab81b3dcd0f6084adac5dbab4caa8f3f4c/src/main/java/net/TheElm/project/CoreMod.java#L90
- As such, enabling block logging will always result in the error in #38
 
(CC: @hatefulbox)

**Comment by GStefanowich** [comment]
Thanks for pointing this out, seems you went through a lot of trouble to figure this out. I'm not sure how it was overlooked that it was defaulted to `true` since it's not implemented. I'll default it to `false` in the next update.

**Comment by GStefanowich** [comment]
Fixed as of `v1.5.1` with commit cd56252bc4905a2e5c4c9ae9345d05d84424f4ea
