### ISSUE TITLE
[Request] Documentation for the config file.

### ISSUE THREAD

**Issue by KS-HTK** [GStefanowich/MC-Server-Protection#47]
Some options in the config file are not very self explainatory, a bit off documentation would be great. Either in the file itself or as a md here on the Git.

**Comment by GStefanowich** [comment]
Most of the config descriptions were recently [added to a CurseForge page](https://www.curseforge.com/minecraft/mc-mods/sewing-machine-utilities/pages/config).

Closing as a duplicate of #8

**Comment by wereii** [comment]
Would it be possible to point the Wiki tab here to that link?
Curseforge pages is the least expected place where I would be searching for wiki, at least for me.
