### ISSUE TITLE
Backpacks causing a crash upon death

### ISSUE THREAD

**Issue by Ilovelinux68** [GStefanowich/MC-Server-Protection#48]
Hello, I noticed that using your mods the server crashes as soon as we get killed by a zombie or any other entity ....

I don't understand why if you can help me?
[crash-2022-02-06_00.25.32-server.txt](https://github.com/GStefanowich/MC-Server-Protection/files/8009114/crash-2022-02-06_00.25.32-server.txt)

**Comment by GStefanowich** [comment]
Looks like an oversight on my part, the contents of a backpack are attempted to be dropped, even if the player doesn't have a backpack. I'll fix it for the next update.

Apologies for the late response, been busy as of late

**Comment by GStefanowich** [comment]
Should be fixed as of `v1.5.1` with commit cd56252bc4905a2e5c4c9ae9345d05d84424f4ea
