### ISSUE TITLE
Not compatible with Minecraft 1.18.2

### ISSUE THREAD

**Issue by hatefulbox** [GStefanowich/MC-Server-Protection#51]
Getting the following Error when launching on 1.18.2 using just Sewing Machine Utilities and Fabric Api 0.47.8

It appears to be an issue with a Mixin, let me know if you want me to try anything and I can let you know how it goes.

https://pastebin.com/2KwHkze2

Thanks!

**Comment by GStefanowich** [comment]
Mojang changed some things around in 1.18.2 that it is not compatible with 1.18/1.18.1, I'll have to update to 1.18.2 when I have the time

**Comment by ghost** [comment]
👀

**Comment by GStefanowich** [comment]
`v1.5.2` has been released for **1.18.2**
