### ISSUE TITLE
(Request) expire death chests option

### ISSUE THREAD

**Issue by ghost** [GStefanowich/MC-Server-Protection#52]
As a server operator I have encountered a problem where new players who become inactive end up leaving many death chests all over the world that are indestructible/obtrusive and an eye sore. I would like a config option that deletes chests after a certain peroid of time (configurable) or maybe allows any players to pick up the chest or just drops the items :)

**Comment by GStefanowich** [comment]
Seems like a good idea. I'll have to add some server options to the next update that allows `all players` or `just OPs` to pick up death chests laying around.

**Comment by GStefanowich** [comment]
This has been added in `v.1.5.2` for 1.18.2, OPs (level 3) or players with the ["interact.death_chest.other" permission](https://github.com/GStefanowich/MC-Server-Protection/blob/657af0c8ae2117a29b0d9a91c2c813963b0013e3/src/main/java/net/TheElm/project/enums/Permissions.java#L61) can now right-click on a death chest to pick it up. Collision pickup is still limited to the player that owns the death chest, to prevent any accidental pickup.
