### ISSUE TITLE
Daily Reward Allowance not being given out

### ISSUE THREAD

**Issue by anthony-mariotti** [GStefanowich/MC-Server-Protection#64]
I was attempting to add currency to my server's economy and noticed users were not getting the daily allowance as specified in the configuration. ~~I skimmed through and found the configuration options in the source code but all I could find was where the option was set to its default value.~~

Would be great to get this working.

**Comment by GStefanowich** [comment]
Are you using any other mods, or a different currency mod by chance?

You can see where [it's implemented at here](https://github.com/GStefanowich/MC-Server-Protection/blob/4ad23835363b5627d5d547e9a797371434aad728/src/main/java/net/theelm/sewingmachine/mixins/Player/ClientInteraction.java#L158). It reads the `LastLogin` of the player, compares it to `Today`, and if it isn't the same day, gives the reward.

**Comment by anthony-mariotti** [comment]
I don't have any other currency mod, I didn't want to add any since this one adds the majority. I'll double-check the configuration to make sure. I have other issues with permissions but I haven't confirmed them yet. 

Modlist:

- architectury-4.4.61
- bettersleeping-0.5.1+1.18
- BlueMap-1.7.2-fabric-1.18
- chat_heads-0.6.0-fabric-1.18.1
- Clumps-fabric-1.18.2-8.0.0+8
- fabric-api-0.53.0+1.18.2
- fabric-language-kotlin-1.7.4+kotlin.1.6.21
- FallingTree-1.18.2-3.5.1
- fastbench-1.18.1-3
- jam-lib-0.0.5
- krypton-0.1.9
- ledger-1.2.4
- ledger-databases-1.1.0
- lithium-fabric-mc1.18.2-0.7.10
- rightclickharvest-2.0.6
- sewing-machine-1.5.2_mc-1.18.2
- spark-1.9.1-fabric
- voicechat-fabric-1.18.2-2.2.32

I'm trying to find a way to test without waiting an entire day.

**Comment by GStefanowich** [comment]
I don't see anything in your mods list that would immediately be the cause of the issue. The only real way to test it to either to wait a day, or edit your players nbt data. Players that don't have a `LastJoin` are considered as "First Join" and are given the initial starting balance.

**Comment by anthony-mariotti** [comment]
... it worked for my player, I just received mine. Not sure what my players were complaining about sorry about the fuss.

**Comment by GStefanowich** [comment]
No worries, people reporting issues is the only way I know to fix things

Thanks for putting in a report
