### ISSUE TITLE
Could not read language file

### ISSUE THREAD

**Issue by 1a2s3d4f1** [GStefanowich/MC-Server-Protection#7]
https://paste.ubuntu.com/p/T5JdcSJcMQ/
client already install Sewing Machine

`[23:25:18] [main/INFO]: [FabricLoader] Loading 61 mods: fabric-renderer-api-v1@0.2.7+f3d8141b95, fabric-keybindings-v0@0.1.1+dfdb52d695, libcd@2.0.1+1.15, fabricloader@0.7.2+build.175, cotton@1.0.0-rc.6, colorunchained@1.0.1, fabric-containers-v0@0.1.3+b7f9825d95, fabric-dimensions-v1@0.2.3+06c939b395, fabric-api-base@0.1.2+b7f9825d95, libblockattributes@0.6.3, cotton-cauldron@1.0.0-rc.6, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d95, simple_pipes@0.3.3, fabric-textures-v0@1.0.4+821cdba795, right-click-clear@1.1.1-unstable.201912010707, fabric-rendering-fluids-v1@0.1.6+12515ed995, cotton-logging@1.0.0-rc.4, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, fabric-renderer-registries-v1@2.0.1+5a0f9a6095, libblockattributes_items@0.6.3, fabric-loot-tables-v1@0.1.5+e08a730595, fabric@0.4.25+build.282-1.15, fabric-particles-v1@0.1.1+dfdb52d695, libblockattributes_core@0.6.3, fabric-networking-v0@0.1.7+12515ed995, cotton-config@1.0.0-rc.4, libnetworkstack@0.3.2, cloth@1.0.1-unstable.201911010702, libmultipart@0.3.3, minecraft@1.15.1, fabric-networking-blockentity-v0@0.2.3+e08a730595, jankson@2.0.0+j1.2.0, sewing-machine@1.1.4, phosphor@0.3.4, cotton-commons@1.0.0-rc.4, fabric-renderer-indigo@0.2.20+d830abd695, fabric-biomes-v1@0.1.5+3b05f68e95, roughlyenoughitems@3.2.21, cotton-datapack@1.0.0-rc.5, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-events-interaction-v0@0.2.6+12515ed995, simple_pipes_dep_container@0.3.3, fabric-rendering-v0@1.0.1+b7f9825d95, cloth-config2@2.5.1, amecs@1.2.9+1.15-pre5, autoconfig1u@1.2.4, fabric-resource-loader-v0@0.1.10+06c939b395, fabric-content-registries-v0@0.1.3+b7f9825d95, fabric-tag-extensions-v0@0.1.3+abd9158095, appleskin@1.0.8, libblockattributes_fluids@0.6.3, fabric-commands-v0@0.1.2+b7f9825d95, fabric-registry-sync-v0@0.2.6+f3d8141b95, foamfix@0.12.1, fabric-mining-levels-v0@0.1.1+b7f9825d95, fabric-events-lifecycle-v0@0.1.2+b7f9825d95, cotton-player-events@1.0.0-rc.4, fabric-item-groups-v0@0.1.6+ec40b2e195, fabric-models-v0@0.1.0+dfdb52d695, badanvil@0.1.0+build.1, fabric-object-builders-v0@0.1.3+e4c9a9c395`

**Comment by GStefanowich** [comment]
Could you provide additional information please?
Please provide the full log/crash report

**Comment by 1a2s3d4f1** [comment]
[2019-12-26-4.log](https://github.com/GStefanowich/MC-Server-Protection/files/4007911/2019-12-26-4.log)

**Comment by GStefanowich** [comment]
Should be fixed in 1.1.5, give it a try and re-open if issue persists.

I should note that from your full log that you're running in offline mode; Claiming chunks uses UUIDs and expects the server to be online in case of username changes. If this is something you would like please open a new feature-request issue.
